#!/usr/bin/env python3
"""Fetch Anthropic model pricing and update cost_collection_service.py.

Sources (tried in order):
1. Anthropic API /models endpoint (requires ANTHROPIC_API_KEY)
2. OpenRouter API (public, but has ~5% markup)
3. Hardcoded fallback values

Run from the installer or manually:
    python scripts/update_model_pricing.py
"""

import json
import re
import sys
from pathlib import Path

# Anthropic's direct pricing (no OpenRouter markup) as of 2026-07-27
# Source: https://docs.anthropic.com/en/docs/about-claude/models
# Cache pricing: write_1h = 2x input, write_5m = 1.25x input, read = 0.1x input
ANTHROPIC_DIRECT_PRICES = {
    "claude-opus-5": {
        "input": 5.0,
        "output": 25.0,
        "cache_write_1h": 10.0,
        "cache_write_5m": 6.25,
        "cache_read": 0.50,
    },
    "claude-opus-4": {
        "input": 15.0,
        "output": 75.0,
        "cache_write_1h": 30.0,
        "cache_write_5m": 18.75,
        "cache_read": 1.50,
    },
    "claude-sonnet-5": {
        "input": 2.0,
        "output": 10.0,
        "cache_write_1h": 4.0,
        "cache_write_5m": 2.50,
        "cache_read": 0.20,
    },
    "claude-sonnet-4": {
        "input": 3.0,
        "output": 15.0,
        "cache_write_1h": 6.0,
        "cache_write_5m": 3.75,
        "cache_read": 0.30,
    },
    "claude-haiku-4.5": {
        "input": 1.0,
        "output": 5.0,
        "cache_write_1h": 2.0,
        "cache_write_5m": 1.25,
        "cache_read": 0.10,
    },
}


def fetch_openrouter_prices():
    """Fetch pricing from OpenRouter API (public, no auth required)."""
    import urllib.request

    try:
        req = urllib.request.Request("https://openrouter.ai/api/v1/models")
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())

        prices = {}
        for m in data.get("data", []):
            mid = m.get("id", "")
            if not mid.startswith("anthropic/claude-"):
                continue

            # Extract base model name (strip anthropic/ prefix)
            model_name = mid.replace("anthropic/", "")

            # Skip aliases
            if model_name.startswith("~"):
                continue

            pricing = m.get("pricing", {})
            inp = float(pricing.get("prompt", 0)) * 1_000_000
            out = float(pricing.get("completion", 0)) * 1_000_000

            if inp <= 0:
                continue

            # Estimate cache pricing (Anthropic's formula)
            cache_write_1h = inp * 2.0
            cache_write_5m = inp * 1.25
            cache_read = inp * 0.1

            prices[model_name] = {
                "input": round(inp, 2),
                "output": round(out, 2),
                "cache_write_1h": round(cache_write_1h, 2),
                "cache_write_5m": round(cache_write_5m, 2),
                "cache_read": round(cache_read, 2),
            }

        return prices
    except Exception as e:
        print(f"  OpenRouter fetch failed: {e}", file=sys.stderr)
        return {}


def normalize_model_name(model_name):
    """Normalize model name for price table lookup."""
    # Strip -fast suffix
    name = re.sub(r"-fast$", "", model_name)
    # Strip trailing version suffix (e.g. -8, -20250514)
    name = re.sub(r"-\d+$", "", name, count=1)
    return name


def write_pricing_json(prices):
    """Write pricing data to config/model_pricing.json."""
    pricing_file = Path(__file__).parent.parent / "config" / "model_pricing.json"
    pricing_file.parent.mkdir(parents=True, exist_ok=True)

    data = {
        "_comment": "Auto-generated by scripts/update_model_pricing.py. Loaded by cost_collection_service.",
        "prices": prices,
    }
    pricing_file.write_text(json.dumps(data, indent=2) + "\n")
    print(f"Wrote {pricing_file}")
    return True


def main():
    print("Updating Anthropic model pricing...")

    # Start with known direct pricing
    prices = dict(ANTHROPIC_DIRECT_PRICES)

    # Try to fetch from OpenRouter for any new models
    print("Fetching from OpenRouter API...")
    or_prices = fetch_openrouter_prices()

    if or_prices:
        # Merge OpenRouter prices, but prefer our direct pricing for known models
        for model, p in or_prices.items():
            normalized = normalize_model_name(model)
            if normalized not in prices and model not in prices:
                prices[model] = p
                print(f"  Added from OpenRouter: {model} (${p['input']}/M in, ${p['output']}/M out)")

    # Write to config/model_pricing.json (never modify source files)
    if write_pricing_json(prices):
        print(f"\nDone! {len(prices)} models in price table.")
        print("\nModels:")
        for name, p in sorted(prices.items()):
            print(f"  {name}: ${p['input']}/M in, ${p['output']}/M out")
    else:
        print("Failed to write pricing JSON", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
