#!/usr/bin/env python3
"""Fetch Anthropic model pricing and update cost_collection_service.py.

Sources (tried in order):
1. Anthropic API /models endpoint (requires ANTHROPIC_API_KEY)
2. OpenRouter API (public, but has ~5% markup)
3. Hardcoded fallback values

Run from the installer or manually:
    python scripts/update_model_pricing.py
"""

import json
import re
import sys
from pathlib import Path

# Anthropic's direct pricing (no OpenRouter markup) as of 2026-07-27
# Source: https://docs.anthropic.com/en/docs/about-claude/models
# Cache pricing: write_1h = 2x input, write_5m = 1.25x input, read = 0.1x input
ANTHROPIC_DIRECT_PRICES = {
    "claude-opus-5": {
        "input": 5.0,
        "output": 25.0,
        "cache_write_1h": 10.0,
        "cache_write_5m": 6.25,
        "cache_read": 0.50,
    },
    "claude-opus-4": {
        "input": 15.0,
        "output": 75.0,
        "cache_write_1h": 30.0,
        "cache_write_5m": 18.75,
        "cache_read": 1.50,
    },
    "claude-sonnet-5": {
        "input": 2.0,
        "output": 10.0,
        "cache_write_1h": 4.0,
        "cache_write_5m": 2.50,
        "cache_read": 0.20,
    },
    "claude-sonnet-4": {
        "input": 3.0,
        "output": 15.0,
        "cache_write_1h": 6.0,
        "cache_write_5m": 3.75,
        "cache_read": 0.30,
    },
    "claude-haiku-4.5": {
        "input": 1.0,
        "output": 5.0,
        "cache_write_1h": 2.0,
        "cache_write_5m": 1.25,
        "cache_read": 0.10,
    },
}


def fetch_openrouter_prices():
    """Fetch pricing from OpenRouter API (public, no auth required)."""
    import urllib.request

    try:
        req = urllib.request.Request("https://openrouter.ai/api/v1/models")
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())

        prices = {}
        for m in data.get("data", []):
            mid = m.get("id", "")
            if not mid.startswith("anthropic/claude-"):
                continue

            # Extract base model name (strip anthropic/ prefix)
            model_name = mid.replace("anthropic/", "")

            # Skip aliases
            if model_name.startswith("~"):
                continue

            pricing = m.get("pricing", {})
            inp = float(pricing.get("prompt", 0)) * 1_000_000
            out = float(pricing.get("completion", 0)) * 1_000_000

            if inp <= 0:
                continue

            # Estimate cache pricing (Anthropic's formula)
            cache_write_1h = inp * 2.0
            cache_write_5m = inp * 1.25
            cache_read = inp * 0.1

            prices[model_name] = {
                "input": round(inp, 2),
                "output": round(out, 2),
                "cache_write_1h": round(cache_write_1h, 2),
                "cache_write_5m": round(cache_write_5m, 2),
                "cache_read": round(cache_read, 2),
            }

        return prices
    except Exception as e:
        print(f"  OpenRouter fetch failed: {e}", file=sys.stderr)
        return {}


def normalize_model_name(model_name):
    """Normalize model name for price table lookup."""
    # Strip -fast suffix
    name = re.sub(r"-fast$", "", model_name)
    # Strip trailing version suffix (e.g. -8, -20250514)
    name = re.sub(r"-\d+$", "", name, count=1)
    return name


def generate_price_table(prices):
    """Generate Python code for the price table."""
    lines = []
    lines.append('    # Price table: $/M tokens')
    lines.append('    # Auto-generated by scripts/update_model_pricing.py')
    lines.append('    # Cache pricing: write_1h = 1.25x input, write_5m = 1.0x input, read = 0.1x input')
    lines.append('    PRICES = {')

    # Sort by model family then name
    def sort_key(item):
        name = item[0]
        # Group by family: opus, sonnet, haiku
        if "opus" in name:
            return (0, name)
        elif "sonnet" in name:
            return (1, name)
        elif "haiku" in name:
            return (2, name)
        else:
            return (3, name)

    sorted_prices = sorted(prices.items(), key=sort_key)

    for i, (model_name, p) in enumerate(sorted_prices):
        is_last = (i == len(sorted_prices) - 1)
        lines.append(f'        "{model_name}": {{')
        lines.append(f'            "input": {p["input"]},')
        lines.append(f'            "output": {p["output"]},')
        lines.append(f'            "cache_write_1h": {p["cache_write_1h"]},')
        lines.append(f'            "cache_write_5m": {p["cache_write_5m"]},')
        lines.append(f'            "cache_read": {p["cache_read"]},')
        if is_last:
            lines.append('        },')
        else:
            lines.append('        },')

    lines.append('    }')
    return "\n".join(lines)


def update_cost_collection_service(prices):
    """Update the PRICES dict in cost_collection_service.py."""
    service_file = Path(__file__).parent.parent / "src" / "services" / "cost_collection_service.py"

    if not service_file.exists():
        print(f"Error: {service_file} not found", file=sys.stderr)
        return False

    content = service_file.read_text()

    # Find the PRICES dict in ClaudeCodeCollector
    # Match from "PRICES = {" line through the matching closing brace
    lines = content.split('\n')
    prices_start = None
    prices_end = None
    brace_depth = 0

    for i, line in enumerate(lines):
        if re.match(r'^\s+PRICES = \{', line):
            prices_start = i
            brace_depth = 0
        if prices_start is not None:
            brace_depth += line.count('{') - line.count('}')
            if brace_depth == 0:
                prices_end = i
                break

    if prices_start is None or prices_end is None:
        print("Error: Could not find PRICES dict in cost_collection_service.py", file=sys.stderr)
        return False

    # Generate new prices and replace lines between start and end (inclusive)
    new_prices_lines = generate_price_table(prices).split('\n')
    new_lines = lines[:prices_start] + new_prices_lines + lines[prices_end + 1:]
    content = '\n'.join(new_lines)

    service_file.write_text(content)
    print(f"Updated {service_file}")
    return True


def main():
    print("Updating Anthropic model pricing...")

    # Start with known direct pricing
    prices = dict(ANTHROPIC_DIRECT_PRICES)

    # Try to fetch from OpenRouter for any new models
    print("Fetching from OpenRouter API...")
    or_prices = fetch_openrouter_prices()

    if or_prices:
        # Merge OpenRouter prices, but prefer our direct pricing for known models
        for model, p in or_prices.items():
            normalized = normalize_model_name(model)
            if normalized not in prices and model not in prices:
                prices[model] = p
                print(f"  Added from OpenRouter: {model} (${p['input']}/M in, ${p['output']}/M out)")

    # Update the service file
    if update_cost_collection_service(prices):
        print(f"\nDone! {len(prices)} models in price table.")
        print("\nModels:")
        for name, p in sorted(prices.items()):
            print(f"  {name}: ${p['input']}/M in, ${p['output']}/M out")
    else:
        print("Failed to update cost_collection_service.py", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
